# base image
FROM python:3.10.6-slim-buster

# WORKDIR /app
# COPY requirements.txt requirements.txt
# COPY customers.py customers.py
# ADD templates templates
# ADD static static

# things to make .py files work
RUN pip3 install --upgrade pip
# RUN pip3 install -r requirements.txt

# ENTRYPOINT python -u -m customers
